#!/usr/bin/env python3
"""
Writes data/ui/emoji_data.js - the list the emoji picker panel shows.

    python tools/make_emoji.py

Python's unicodedata has no emoji tables, so the picker uses Unicode's own character names as search words and a hand-made
list of blocks per group.  Only code points Python knows by name are included.  The output is a single JavaScript file:
    window.EMOJI = [ ["<char>", "<lower-case name>", "<group id>"], ... ];
    window.EMOJI_GROUPS = [ ["smileys", "Smileys & people", "<icon char>"], ... ];
"""
import json
import os
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "data", "ui", "emoji_data.js")

# (group id, title, tab icon, [ (first, last) code point ranges ])
GROUPS = [
    ("smileys", "Smileys & people", "\U0001F600", [
        (0x1F600, 0x1F64F), (0x1F910, 0x1F92F), (0x1F970, 0x1F976), (0x1F978, 0x1F97A), (0x1F9D0, 0x1F9D0),
        (0x1F440, 0x1F450), (0x1F466, 0x1F487), (0x1F4AA, 0x1F4AA), (0x1F90C, 0x1F90F), (0x1F932, 0x1F93A),
        (0x1F9D1, 0x1F9DF), (0x1F9E0, 0x1F9E0), (0x1FAC0, 0x1FAC5), (0x1FAE0, 0x1FAE7)]),
    ("nature", "Animals & nature", "\U0001F431", [
        (0x1F400, 0x1F43F), (0x1F980, 0x1F9AE), (0x1F330, 0x1F344), (0x1F490, 0x1F490), (0x1F4AE, 0x1F4AE),
        (0x1F338, 0x1F33F), (0x1FAB0, 0x1FABD), (0x1F9A0, 0x1F9A0)]),
    ("food", "Food & drink", "\U0001F355", [
        (0x1F345, 0x1F37F), (0x1F950, 0x1F96F), (0x1F9C0, 0x1F9CB), (0x1FAD0, 0x1FAD9)]),
    ("activity", "Activities", "⚽", [
        (0x1F380, 0x1F393), (0x1F3A0, 0x1F3CA), (0x1F3CF, 0x1F3D3), (0x1F3F8, 0x1F3F9), (0x1F93B, 0x1F94F),
        (0x1F9E7, 0x1F9FF), (0x1F004, 0x1F004), (0x1F0CF, 0x1F0CF)]),
    ("travel", "Travel & places", "\U0001F680", [
        (0x1F30D, 0x1F32C), (0x1F3D4, 0x1F3F0), (0x1F680, 0x1F6C5), (0x1F6CB, 0x1F6D2), (0x1F6D5, 0x1F6D7),
        (0x1F6E0, 0x1F6EC), (0x1F6F0, 0x1F6FC), (0x1F5FA, 0x1F5FF), (0x1F300, 0x1F30C)]),
    ("objects", "Objects", "\U0001F4A1", [
        (0x1F4A1, 0x1F4A9), (0x1F4B0, 0x1F4FF), (0x1F50A, 0x1F52F), (0x1F550, 0x1F567), (0x1F5A4, 0x1F5A4),
        (0x1F9E0, 0x1F9E6), (0x1F9F0, 0x1F9F6), (0x1FA70, 0x1FA7C), (0x1FA80, 0x1FA88), (0x1FA90, 0x1FABA)]),
    ("symbols", "Symbols", "❤", [
        (0x1F493, 0x1F49F), (0x1F4A2, 0x1F4A8), (0x1F500, 0x1F50A), (0x1F530, 0x1F53D), (0x1F5A4, 0x1F5A4),
        (0x1F7E0, 0x1F7EB)]),
]
# single characters from the Basic Multilingual Plane that are emoji (the classic text-style symbols)
BMP = {
    "smileys": "☺☹✋✌☝✊✍",
    "nature": "☀☁☂☃☄⛄⛅⚡❄✨⭐☔☘☢☣",
    "activity": "⚽⚾⛳⛷⛸⛹♟♠♣♥♦",
    "travel": "✈⛵⛴⛽⚓⌚⌛⏰⏱⏲♨⛩⛪⛲⛺",
    "objects": "☎✉✏✒✂⚙⚔⛏⛓⚖⚗⚰⚱",
    "symbols": "❤❣✅❌❎❗❓❕❔‼⁉➕➖➗✔✖⬆⬇⬅➡↔↕↩↪♻⚛♀♂☢☮☯☸✡✳✴❇⚠⛔⚪⚫",
}
SKIP_WORDS = ("VARIATION SELECTOR", "ZERO WIDTH", "EMOJI MODIFIER", "REGIONAL INDICATOR", "TAG ", "KEYCAP")


def add(rows, seen, gid, ch):
    if ch in seen:
        return
    try:
        name = unicodedata.name(ch)
    except ValueError:
        return
    if any(w in name for w in SKIP_WORDS):
        return
    seen.add(ch)
    rows.append([ch, name.lower(), gid])


def main():
    rows, seen = [], set()
    for gid, _title, _icon, ranges in GROUPS:
        for lo, hi in ranges:
            for cp in range(lo, hi + 1):
                add(rows, seen, gid, chr(cp))
        for ch in BMP.get(gid, ""):
            add(rows, seen, gid, ch)
    groups = [[g[0], g[1], g[2]] for g in GROUPS]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("// generated by tools/make_emoji.py - do not edit\n")
        fh.write("window.EMOJI_GROUPS = %s;\n" % json.dumps(groups, ensure_ascii=False))
        fh.write("window.EMOJI = [\n")
        fh.write(",\n".join(json.dumps(r, ensure_ascii=False) for r in rows))
        fh.write("\n];\n")
    print("wrote", os.path.normpath(OUT), "-", len(rows), "emoji")


if __name__ == "__main__":
    main()
