#!/usr/bin/env python3
"""
Generates NeonScript's holiday themes into data/themes.ini.

Every holiday theme brings its own 16 first colours (rgb=, the way MTS themes do) so its colours are exact; the other 83 colours
of the palette are mIRC's fixed ones.  The 16 slots keep the meaning chat colour codes have everywhere (4 is a red, 3 a green,
12 a blue, 8 a yellow ...), tinted to the holiday.

    python tools/make_holiday_themes.py            rewrite the holiday block of data/themes.ini and print a contrast report
    python tools/make_assets.py                    (separately) draws the gallery pictures for them

Slots:  0 bright text   1 background   2 panel   3 green   4 red   5 dark red   6 purple   7 orange   8 yellow/gold   9 light green
        10 teal   11 ice/cyan   12 blue   13 pink   14 dim text   15 soft text
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
INI = os.path.normpath(os.path.join(HERE, "..", "data", "themes.ini"))
BEGIN = "; ---- holiday themes: generated by tools/make_holiday_themes.py (edit the script, not this block) ----"
END = "; ---- end of holiday themes ----"

ITEMS = ["Background", "Action", "Ctcp", "Highlight", "Info", "Info2", "Invite", "Join", "Kick", "Mode", "Nick", "Normal", "Notice",
         "Notify", "Other", "Own", "Part", "Quit", "Topic", "Wallops", "Whois", "Editbox", "Editbox text", "Listbox", "Listbox text",
         "Gray text", "Title text", "Inactive", "Treebar", "Treebar Text", "MDI area"]
EVKEYS = ["join", "part", "quit", "kick", "mode", "topic", "nick", "invite", "label", "value", "dim", "hi", "q", "a", "o", "h", "v"]

# what every dark holiday theme starts from (slot numbers); each theme overrides a few
DARK = dict(
    Background=1, Action=13, Ctcp=10, Highlight=8, Info=11, Info2=15, Invite=12, Join=9, Kick=4, Mode=7, Nick=11, Normal=0, Notice=6,
    Notify=8, Other=15, Own=11, Part=7, Quit=13, Topic=8, Wallops=13, Whois=15, Editbox=2, **{"Editbox text": 0}, Listbox=2,
    **{"Listbox text": 15}, **{"Gray text": 14}, **{"Title text": 0}, Inactive=2, Treebar=1, **{"Treebar Text": 15}, **{"MDI area": 1},
)
# light themes (a pale background, dark text)
LIGHT = dict(
    Background=0, Action=13, Ctcp=10, Highlight=7, Info=12, Info2=14, Invite=6, Join=3, Kick=4, Mode=7, Nick=12, Normal=1, Notice=6,
    Notify=7, Other=14, Own=12, Part=7, Quit=4, Topic=6, Wallops=13, Whois=1, Editbox=0, **{"Editbox text": 1}, Listbox=2,
    **{"Listbox text": 1}, **{"Gray text": 14}, **{"Title text": 1}, Inactive=2, Treebar=2, **{"Treebar Text": 1}, **{"MDI area": 2},
)
# NeonScript's own event colours, by slot
EV_DARK = dict(join=9, part=7, quit=13, kick=4, mode=8, topic=11, nick=11, invite=12, label=14, value=0, dim=14, hi=8, q=8, a=4, o=9, h=11, v=13)
EV_LIGHT = dict(join=3, part=7, quit=4, kick=4, mode=7, topic=6, nick=12, invite=6, label=14, value=1, dim=14, hi=7, q=6, a=4, o=3, h=12, v=13)

THEMES = [
    dict(id="h_newyear", name="New Year's Eve", mode="dark", accent=8, acc1="#ffd166", acc2="#a58bff",
         desc="Midnight navy, champagne gold and a little confetti. Counting down.",
         pal="fff6e0 080c24 141b45 5fd6a4 ff5d73 7a2b4a a58bff ff9f43 ffd166 a8f0c6 3ec6c0 7fe3ff 6c8cff ff7eb6 7d86ab c9d0ea",
         over=dict(Highlight=8, Mode=13, Topic=11, Notice=6, Action=13, Kick=4), ev=dict(mode=13, hi=8, q=8),
         nicks=[3, 6, 7, 8, 9, 10, 11, 12, 13, 15]),
    dict(id="h_valentine", name="Valentine's Day", mode="dark", accent=13, acc1="#ff4d6d", acc2="#ff9fc2",
         desc="Deep wine with rose, blush and a touch of cream. Hearts optional.",
         pal="fff0f4 17060d 2a0d1b 7fd6a0 ff4d6d 8b1e3f c77dff ff9770 ffd6a5 b8f2c9 4fd1c5 9be7ff 7aa2ff ff8fb8 a07a89 e6c9d3",
         over=dict(Highlight=13, Action=13, Mode=8, Topic=7, Join=9, Part=7, Quit=4, Kick=4, Notice=6, Nick=13, Own=11),
         ev=dict(join=9, part=7, quit=4, mode=8, topic=7, nick=13, hi=13, q=13, a=4, o=9, h=11, v=8),
         nicks=[3, 6, 7, 8, 9, 10, 11, 12, 13, 15]),
    dict(id="h_stpatrick", name="St. Patrick's Day", mode="dark", accent=3, acc1="#2ecc71", acc2="#ffd23f",
         desc="Shamrock greens on forest black, with gold at the end of the rainbow.",
         pal="f3ffe9 06140b 0e2a17 2ecc71 ff6b57 7a4a1e b388ff ff9f1c ffd23f 9cf29c 26b5a0 8ff0e0 5aa9ff ff9ecb 6f917a cfe8d4",
         over=dict(Highlight=8, Join=3, Part=7, Quit=13, Mode=8, Topic=9, Nick=9, Own=11, Action=9, Notice=8, Info=9),
         ev=dict(join=3, part=7, quit=13, mode=8, topic=9, nick=9, hi=8, q=8, a=4, o=3, h=9, v=11),
         nicks=[3, 6, 7, 8, 9, 10, 11, 12, 13, 15]),
    dict(id="h_easter", name="Easter", mode="light", accent=6, acc1="#b39ddb", acc2="#7fcfc2",
         desc="Pastel lilac, mint and butter yellow on warm cream. A light theme.",
         pal="fffaf2 3b2f4a efe8ff 27804f c0355b 8a4b5a 7a55c4 b0520e 8a6500 7ccf9c 177c79 1e7096 3d63c4 b83a76 7a7286 6b6178",
         over=dict(Highlight=6, Action=13, Notice=12, Info=10, Invite=6, Topic=12, Mode=7, Nick=6, Own=12, Part=7, Quit=4),
         ev=dict(join=3, part=7, quit=4, mode=7, topic=12, nick=6, hi=6, q=6, a=4, o=3, h=10, v=13),
         nicks=[3, 4, 6, 7, 10, 11, 12, 13], light=True),
    dict(id="h_memorial", name="Memorial Day", mode="dark", accent=4, acc1="#e2453c", acc2="#8ecaff",
         desc="Navy night, poppy red and white. Quiet and dignified.",
         pal="f5f7fb 091226 12203f 6fbf8a e2453c 7b1e2b 9a8cff f29a4a f3d27a a7e0b8 4fb3bf 8ecaff 4d86e8 e58fb0 7f8db0 c5cde2",
         over=dict(Highlight=4, Action=11, Mode=8, Topic=11, Notice=15, Nick=11, Own=11, Join=9, Part=7, Quit=13, Info=11),
         ev=dict(join=9, part=7, quit=13, mode=8, topic=11, nick=11, hi=4, q=4, a=8, o=9, h=11, v=15),
         nicks=[3, 6, 7, 8, 9, 10, 11, 12, 13, 15]),
    dict(id="h_juneteenth", name="Juneteenth", mode="dark", accent=8, acc1="#e0443a", acc2="#f7b32b",
         desc="Red, gold and green on black - the colours of the celebration.",
         pal="fff4dc 0d0d0d 1e1a14 2fa561 e0443a 7c2a1f b08cff f28c28 f7b32b 8fe3a8 35b0a0 8fd8ff 5a8dee f08cb0 8a8071 d9ceb9",
         over=dict(Highlight=8, Action=8, Mode=7, Topic=9, Notice=8, Nick=8, Own=9, Join=9, Part=7, Quit=4, Kick=4, Info=9),
         ev=dict(join=9, part=7, quit=4, mode=7, topic=9, nick=8, hi=8, q=8, a=4, o=3, h=9, v=15),
         nicks=[3, 6, 7, 8, 9, 10, 11, 12, 13, 15]),
    dict(id="h_july4", name="Independence Day", mode="dark", accent=4, acc1="#ff4757", acc2="#3d8bff",
         desc="Fireworks over a navy sky: red, white and bright blue with a gold spark.",
         pal="ffffff 071230 102050 4fd18b ff4757 8a1c2c a68cff ff9f43 ffd84d a5f0c1 37c3c3 8fd6ff 3d8bff ff8fb1 7b8bb8 cdd6ee",
         over=dict(Highlight=4, Action=12, Mode=8, Topic=11, Notice=15, Nick=11, Own=12, Join=9, Part=7, Quit=13, Info=11),
         ev=dict(join=9, part=7, quit=13, mode=8, topic=11, nick=11, hi=4, q=8, a=4, o=12, h=11, v=15),
         nicks=[3, 6, 7, 8, 9, 10, 11, 12, 13, 15]),
    dict(id="h_labor", name="Labor Day", mode="dark", accent=7, acc1="#ff8a1f", acc2="#5b8fc7",
         desc="Work-shirt denim, safety orange and hard-hat yellow.",
         pal="f2f5f8 0d1722 16273a 6dbb7c e5604d 8a3b2a 9d8cd8 ff8a1f ffc83d a6dcae 4aa9a6 8cc9e6 5b8fc7 e690aa 7d8ea0 c4cfda",
         over=dict(Highlight=7, Action=12, Mode=8, Topic=11, Notice=15, Nick=11, Own=12, Join=9, Part=7, Quit=13, Info=11),
         ev=dict(join=9, part=7, quit=13, mode=8, topic=11, nick=11, hi=7, q=8, a=4, o=7, h=12, v=15),
         nicks=[3, 6, 7, 8, 9, 10, 11, 12, 13, 15]),
    dict(id="h_halloween", name="Halloween", mode="dark", accent=7, acc1="#ff7518", acc2="#9b5de5",
         desc="Near-black purple, pumpkin orange, witch purple and slime green.",
         pal="f4ecd8 0a0610 1a1026 8ae234 e83c3c 5c1a1a 9b5de5 ff7518 ffc233 b6f06a 2fb7a0 8fe8ff 6c7bff ff6fb5 8b7a99 cdbfd9",
         over=dict(Highlight=7, Action=6, Mode=6, Topic=8, Notice=7, Nick=9, Own=11, Join=9, Part=7, Quit=4, Kick=4, Info=6),
         ev=dict(join=9, part=7, quit=13, mode=6, topic=8, nick=9, hi=7, q=7, a=4, o=9, h=6, v=8),
         nicks=[3, 6, 7, 8, 9, 10, 11, 12, 13, 15]),
    dict(id="h_thanksgiving", name="Thanksgiving", mode="dark", accent=7, acc1="#e2711d", acc2="#f2b84b",
         desc="Dark chocolate with burnt orange, harvest gold, cranberry and sage.",
         pal="fbf0dc 150d08 27170d 8fae6b e0493d 6e2b1d 9c7bb8 e2711d f2b84b b5cf8f 4ea58f 8fcfe0 6d93c9 e08aa0 98836e d8c7ad",
         over=dict(Highlight=7, Action=8, Mode=8, Topic=3, Notice=7, Nick=8, Own=9, Join=3, Part=7, Quit=13, Kick=4, Info=9),
         ev=dict(join=3, part=7, quit=13, mode=8, topic=9, nick=8, hi=7, q=8, a=4, o=3, h=9, v=7),
         nicks=[3, 6, 7, 8, 9, 10, 11, 12, 13, 15]),
    dict(id="h_hanukkah", name="Hanukkah", mode="dark", accent=12, acc1="#4d8dff", acc2="#f7c948",
         desc="Royal blue and silver with the gold of the menorah flames.",
         pal="ffffff 050f2b 0c1e4e 5fd1a0 ff6b7a 6b2a5e 9d8cff ffa94d f7c948 a6efc9 35c0cf 9ee1ff 3f7bff ff93c0 7c8fc4 d6def2",
         over=dict(Highlight=8, Action=12, Mode=8, Topic=11, Notice=15, Nick=11, Own=12, Join=9, Part=7, Quit=13, Info=11),
         ev=dict(join=9, part=7, quit=13, mode=8, topic=11, nick=11, hi=8, q=8, a=12, o=9, h=11, v=15),
         nicks=[3, 6, 7, 8, 9, 10, 11, 12, 13, 15]),
    dict(id="h_christmas", name="Christmas", mode="dark", accent=4, acc1="#e03a3e", acc2="#2fbf71",
         desc="Evergreen night, holly red, snow white and gold.",
         pal="f7fbff 06170e 0e2a1b 2fbf71 ea4a4e 7a1f2b a98be0 f08a24 ffd166 8fe3a8 2aa6a0 a5dcff 5a9bff ff8fb0 7f9a8a d0e0d6",
         over=dict(Highlight=8, Action=8, Mode=8, Topic=11, Notice=0, Nick=3, Own=11, Join=3, Part=8, Quit=4, Kick=4, Info=3),
         ev=dict(join=3, part=8, quit=4, mode=8, topic=11, nick=3, hi=8, q=8, a=4, o=3, h=11, v=0),
         nicks=[3, 6, 7, 8, 9, 10, 11, 12, 13, 15]),
]


def hexrgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def lum(c):
    def f(v):
        v /= 255.0
        return v / 12.92 if v <= 0.03928 else ((v + 0.055) / 1.055) ** 2.4
    r, g, b = c
    return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b)


def contrast(a, b):
    la, lb = lum(a), lum(b)
    if la < lb:
        la, lb = lb, la
    return (la + 0.05) / (lb + 0.05)


def build(t):
    pal = [hexrgb(x) for x in t["pal"].split()]
    assert len(pal) == 16, t["id"]
    light = t.get("light", False)
    role = dict(LIGHT if light else DARK)
    role.update(t.get("over", {}))
    cols = [role[i] for i in ITEMS]
    ev = dict(EV_LIGHT if light else EV_DARK)
    ev.update(t.get("ev", {}))
    evs = ",".join("%s:%d" % (k, ev[k]) for k in EVKEYS)
    nick = " ".join(str(n) for n in t["nicks"])
    rgb = " ".join("%d,%d,%d" % c for c in pal)
    return pal, role, ev, cols, evs, nick, rgb


def report(t, pal, role, ev):
    bg = pal[role["Background"]]
    lines = []
    bad = 0

    def chk(label, slot, need, against=bg):
        nonlocal bad
        r = contrast(pal[slot], against)
        flag = "" if r >= need else "   <-- LOW"
        if flag:
            bad += 1
        lines.append("    %-12s slot %-2d %.1f:1 (need %.1f)%s" % (label, slot, r, need, flag))

    chk("Normal", role["Normal"], 7)
    for k in ("Action", "Join", "Part", "Quit", "Kick", "Mode", "Topic", "Notice", "Nick", "Own", "Highlight", "Info", "Invite", "Whois", "Notify", "Wallops"):
        chk(k, role[k], 4.5)
    chk("Gray text", role["Gray text"], 3.0)
    chk("Listbox text", role["Listbox text"], 4.5, pal[role["Listbox"]])
    chk("Editbox text", role["Editbox text"], 7, pal[role["Editbox"]])
    chk("Treebar text", role["Treebar Text"], 4.5, pal[role["Treebar"]])
    for k in ("join", "part", "quit", "kick", "mode", "topic", "nick", "invite", "q", "a", "o", "h", "v"):
        chk("ev " + k, ev[k], 3.0)
    for n in t["nicks"]:
        chk("nick %d" % n, n, 4.5)
    return lines, bad


def write():
    out = [BEGIN]
    for t in THEMES:
        pal, role, ev, cols, evs, nick, rgb = build(t)
        out += ["", "[%s]" % t["id"], "name=%s" % t["name"], "desc=%s" % t["desc"], "mode=%s" % t["mode"], "accent=%d" % t["accent"],
                "acc1=%s" % t["acc1"], "acc2=%s" % t["acc2"], "colors=%s" % ",".join(str(c) for c in cols), "ev=%s" % evs,
                "nickcols=%s" % nick, "rgb=%s" % rgb]
    out += ["", END, ""]
    block = "\n".join(out)
    s = open(INI, encoding="utf-8").read().replace("\r\n", "\n")
    if BEGIN in s:
        s = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", lambda m: block, s, flags=re.S)
    else:
        s = s.rstrip("\n") + "\n\n" + block
    ids = ",".join(t["id"] for t in THEMES)
    m = re.search(r"^order=(.*)$", s, re.M)
    base = [x for x in m.group(1).split(",") if not x.startswith("h_")]
    s = s[:m.start()] + "order=" + ",".join(base + ids.split(",")) + s[m.end():]
    open(INI, "w", encoding="utf-8", newline="").write(s.replace("\n", "\r\n"))


if __name__ == "__main__":
    total = 0
    for t in THEMES:
        pal, role, ev, cols, evs, nick, rgb = build(t)
        lines, bad = report(t, pal, role, ev)
        total += bad
        print("%s  (%s)  background #%02x%02x%02x  low-contrast items: %d" % (t["name"], t["id"], *pal[role["Background"]], bad))
        for l in lines:
            if "LOW" in l:
                print(l)
    write()
    print("wrote %d holiday themes into %s (%d contrast warnings)" % (len(THEMES), INI, total))
